import {Roulette} from './models';

export class Constants {
  public static rouletteNumbers: Roulette[] = [
    { value: 0, color: "Green" },
    { value: 26, color: "Black" },
    { value: 3, color: "Red" },
    { value: 35, color: "Black" },
    { value: 12, color: "Red" },
    { value: 28, color: "Black" },
    { value: 7, color: "Red" },
    { value: 29, color: "Black" },
    { value: 18, color: "Red" },
    { value: 22, color: "Black" },
    { value: 9, color: "Red" },
    { value: 31, color: "Black" },
    { value: 14, color: "Red" },
    { value: 20, color: "Black" },
    { value: 1, color: "Red" },
    { value: 33, color: "Black" },
    { value: 16, color: "Red" },
    { value: 24, color: "Black" },
    { value: 5, color: "Red" },
    { value: 10, color: "Black" },
    { value: 23, color: "Red" },
    { value: 8, color: "Black" },
    { value: 30, color: "Red" },
    { value: 11, color: "Black" },
    { value: 36, color: "Red" },
    { value: 13, color: "Black" },
    { value: 27, color: "Red" },
    { value: 6, color: "Black" },
    { value: 34, color: "Red" },
    { value: 17, color: "Black" },
    { value: 25, color: "Red" },
    { value: 2, color: "Black" },
    { value: 21, color: "Red" },
    { value: 4, color: "Black" },
    { value: 19, color: "Red" },
    { value: 15, color: "Black" },
    { value: 32, color: "Red" }
  ];}
